server:
  port: 80

spring:
  application:
    name: sc-demo-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: sc-demo-zuul-80

# zuulpe配置
zuul:
  routes:
    mydept.serviceId: sc-demo-provider-dept
    mydept.path: /mydept/**     #如果不指定路由，通过服务名称访问，例如http://127.0.0.1/sc-demo-provider-dept/provider/dept/get/4。如果指定了路由，使用指定路径访问，例如：http://127.0.0.1/mydept/provider/dept/get/4
  ignored-services: "*"         #忽略指定服务使用服务名作为路径访问，*代表忽略所有服务。本来将不能使用http://127.0.0.1/sc-demo-provider-dept/provider/dept/get/4访问

# actuator info信息配置
info:
  app:
    name: 部门服务
    author: jiangbaojun
  company: spring1
