# 服务配置
server:
  port: 8081

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.sc.api

# spring配置
spring:
  application:
    name: sc-demo-provider-dept #相同服务的name必须要相同
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678

# eureka配置
eureka:
  client:
    service-url:
#      单机配置
#      defaultZone: http://127.0.0.1:7001/eureka/
#      集群配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: sc-demo-provider-dept8081 #eureka客户端示例id，对应监控页面status的显示值

# actuator info信息配置
info:
  app:
    name: 部门服务
    author: jiangbaojun
  company: spring1