# 服务配置
server:
  port: 7001

# eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #表示自己是注册中心
    service-url:
#       单机配置
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群配置，在监控页面，默认显示的是此处的IP（域名）本机配置了3个host为127.0.0.1
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/